config/routes.rb
YelpClone::Application.routes.draw do

  get "reviews/new"
  resources :restaurants do 
    resources :reviews
  end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :reviews

	def average_score
		return 'No reviews' if reviews.none? 
		reviews.average(:rating)
	end
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :restaurant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController


	def index
		@restaurants = Restaurant.all
	end

	def new
		@restaurant = Restaurant.new
	end
	
	def create
		Restaurant.create restaurant_params
		redirect_to '/restaurants'
	end

	def edit
		@restaurant = Restaurant.find params[:id]
	end

	def update
		@restaurant = Restaurant.find params[:id]

		@restaurant.update restaurant_params
		flash[:notice] = 'Restaurant updated successfully'
		redirect_to '/restaurants'
	end

	def destroy
		@restaurant = Restaurant.find params[:id]
		@restaurant.destroy
		
		flash[:notice] = 'Restaurant deleted successfully'
		redirect_to '/restaurants'
	end

	private

	def restaurant_params
		params[:restaurant].permit(:name,  :location, :category)
	end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  
  def new
  	@restaurant = Restaurant.find params[:restaurant_id]
  	@review = Review.new
  end

  def create
  	@restaurant = Restaurant.find params[:restaurant_id]
  	@restaurant.reviews.create params[:review].permit(:comment, :rating)
  	redirect_to '/restaurants'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YelpClone</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= notice %>
<%= yield %>

</body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>

	<%= f.label :category %>
	<%= f.text_field :category %>

	<%= f.label :location %>
	<%= f.text_field :location %>

	<%= f.submit %>
<% end %> 

app/views/restaurants/edit.html.erb
<%= render 'form' %>

app/views/restaurants/index.html.erb
<% if @restaurants.any? %>
	<% @restaurants.each do |restaurant| %>
		<%= restaurant.name %><br>
		<%= link_to 'Edit', edit_restaurant_path(restaurant) %>
		<%= link_to "Delete #{restaurant.name}", restaurant_path(restaurant), method: :delete, data: { confirm: 'Are you sure'} %>
		<%= link_to "Review #{restaurant.name}",new_restaurant_review_path(restaurant)%>

		<h3 class='average_review '>
			<%= restaurant.average_score %>
		</h3>
	<% end %>
<% else %>
	No restaurants yet
<% end %>

<%= link_to 'Add a restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<%= form_for @restaurant do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>

	<%= f.label :category %>
	<%= f.text_field :category %>

	<%= f.label :location %>
	<%= f.text_field :location %>

	<%= f.submit %>
<% end %>

app/views/reviews/new.html.erb
<%= form_for [@restaurant, @review] do |f| %>
	<%= f.label  :comment %>
	<%= f.text_area :comment %>

	<br>

	<%= f.label :rating %>
	<%= f.select :rating, 1..5 %>

	<%= f.submit %>
<% end %>